### ISSUE TITLE
Errors in console on running npm run serve

### ISSUE THREAD

**Issue by connecteev** [xinnks/xns-audio-player#6]
Errors in console on running ```npm run serve```

```
Module Warning (from ./node_modules/eslint-loader/index.js):
error: Mixed spaces and tabs (no-mixed-spaces-and-tabs) at src/components/PersistentPlayer.vue:23:2:
  21 | 							<SkipForwardIcon class="cursor-pointer text-white" w="30" h="30"/>
  22 | 						</div>
> 23 | 		          	</div>
     | 	^
  24 | 		          	<div class="inline-flex flex-row w-full items-center justify-between px-4 py-1">
  25 | 						<div class="flex-1 w-3/4">
  26 | 							<vue-slider :width="150" :duration="0.1" :min="0" :max="1" v-model="playerVolume" :process="true" :interval="0.01"></vue-slider>


error: Mixed spaces and tabs (no-mixed-spaces-and-tabs) at src/components/PersistentPlayer.vue:24:2:
  22 | 						</div>
  23 | 		          	</div>
> 24 | 		          	<div class="inline-flex flex-row w-full items-center justify-between px-4 py-1">
     | 	^
  25 | 						<div class="flex-1 w-3/4">
  26 | 							<vue-slider :width="150" :duration="0.1" :min="0" :max="1" v-model="playerVolume" :process="true" :interval="0.01"></vue-slider>
  27 | 						</div>


error: Mixed spaces and tabs (no-mixed-spaces-and-tabs) at src/components/PersistentPlayer.vue:31:2:
  29 | 							<span v-tooltip.top-center="continuousPlay ? 'Repeat: ALL' : 'Repeat: OFF'" @click="changeContinuousPlay()" :class="continuousPlay ? 'bg-transparent float-right text-white text-primary-green' : 'bg-transparent float-right text-white text-white'"><RefreshIcon w="30" h="30"/></span>
  30 | 						</div>
> 31 | 		            </div>
     | 	^
  32 | 				</div>
  33 | 			</div>
  34 | 			<div class="flex-grow w-full md:w-2/3 lg:w-3/4 xl:w-4/5 playing-progress m-0 px-3 sm:p-12 h-16 sm:h-auto md:h-full lg:h-full xl:h-full">


error: Mixed spaces and tabs (no-mixed-spaces-and-tabs) at src/components/PersistentPlayer.vue:59:2:
  57 | Vue.use(VTooltip);
  58 | export default {
> 59 |   	name: 'PersistentPlayer',
     |  ^
  60 | 	components: {
  61 | 	    RefreshIcon,SkipBackwardIcon, PlayIcon, PauseIcon, SquareIcon, SkipForwardIcon, VueSlider, CloseIcon, RevealIcon, VTooltip
  62 | 	},


error: Mixed spaces and tabs (no-mixed-spaces-and-tabs) at src/components/PersistentPlayer.vue:61:2:
  59 |   	name: 'PersistentPlayer',
  60 | 	components: {
> 61 | 	    RefreshIcon,SkipBackwardIcon, PlayIcon, PauseIcon, SquareIcon, SkipForwardIcon, VueSlider, CloseIcon, RevealIcon, VTooltip
     | 	^
  62 | 	},
  63 | 	mixins: [PlayerMixin],
  64 | 	data(){


error: The "VTooltip" component has been registered but not used (vue/no-unused-components) at src/components/PersistentPlayer.vue:61:120:
  59 |   	name: 'PersistentPlayer',
  60 | 	components: {
> 61 | 	    RefreshIcon,SkipBackwardIcon, PlayIcon, PauseIcon, SquareIcon, SkipForwardIcon, VueSlider, CloseIcon, RevealIcon, VTooltip
     | 	                                                                                                                      ^
  62 | 	},
  63 | 	mixins: [PlayerMixin],
  64 | 	data(){


6 errors found.
```

**Comment by xinnks** [comment]
For the moment you can either turn es-lint off or rectify the spacing in your local repo. I'll deal with that when I'm back in my office.

**Comment by xinnks** [comment]
@connecteev I've fixed the spacing errors.
